#!/usr/bin/env python3
"""
Offline unit tests for CLI wrapper SSO-awareness and read-only enforcement
(modern-cloud-auth tasks 2.4 and 3.4).

Covers:
- 2.4a SSO passthrough: when the workspace config carries SSO keys, a role
  binding, or a recorded session, the aws wrapper must NOT override the
  Session Broker's scoped AWS_CONFIG_FILE with its own static temp config
- 2.4a static path: workspaces with no SSO config keep the exact legacy
  behavior (wrapper-generated temp config with credential_process)
- 2.4b expired-session hint: one-line stderr hint (workspace name +
  "session expired — run: nubifer-creds login -t <provider>") when the
  recorded session expiry is past; never blocks the command; same cheap
  check in the az and gcloud wrappers
- 3.4 read-only enforcement ordering: write verbs are blocked identically
  in all three credential paths (static temp-config, SSO passthrough,
  role-profile) and the block fires BEFORE any credential resolution or
  session/expiry logic

The wrappers are bash scripts, so each test runs a temp copy of the wrapper
with the hardcoded provider binary (/usr/bin/aws etc.) substituted for a
recorder stub — no real cloud CLI, no network, no gpg/pass (stubbed on
PATH), isolated temp HOME. Workspace config files are plain temp JSON.
"""

import json
import os
import shutil
import stat
import subprocess
import tempfile
import unittest
from datetime import datetime, timedelta, timezone
from pathlib import Path

WRAPPER_DIR = Path(__file__).resolve().parent.parent / 'cli-wrappers'

WORKSPACE_ID = 'ws-test-1234'
WORKSPACE_NAME = 'alpha'

RECORDER_STUB = """#!/bin/bash
# Test stub standing in for the real provider CLI binary
{
  echo "ARGS: $*"
  echo "AWS_CONFIG_FILE: ${AWS_CONFIG_FILE:-}"
  echo "NUBIFER_WORKSPACE: ${NUBIFER_WORKSPACE:-}"
  if [ -n "${AWS_CONFIG_FILE:-}" ] && [ -f "$AWS_CONFIG_FILE" ]; then
    echo "--CONFIG--"
    cat "$AWS_CONFIG_FILE"
  fi
} > "$NUBIFER_TEST_RECORD"
exit 0
"""


def _iso(delta_hours):
    """ISO 8601 'Z' timestamp offset from now (matches AWS SSO cache style)"""
    ts = datetime.now(timezone.utc) + timedelta(hours=delta_hours)
    return ts.strftime('%Y-%m-%dT%H:%M:%SZ')


class WrapperTestBase(unittest.TestCase):
    """Isolated HOME + stubbed provider binary/pass for wrapper runs."""

    provider = 'aws'          # wrapper filename
    real_binary = '/usr/bin/aws'

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix='nubifer-wrapper-test-'))
        self.home = self.tmp / 'home'
        self.stub_bin = self.tmp / 'bin'
        self.record = self.tmp / 'record.txt'
        self.home.mkdir()
        self.stub_bin.mkdir()

        # Recorder stub replaces the hardcoded provider binary path
        self.cli_stub = self.stub_bin / f'{self.provider}-real'
        self.cli_stub.write_text(RECORDER_STUB)
        self._make_executable(self.cli_stub)

        # 'pass' stub so the static path's GPG pre-warm is a silent no-op
        pass_stub = self.stub_bin / 'pass'
        pass_stub.write_text('#!/bin/bash\nexit 0\n')
        self._make_executable(pass_stub)

        # Temp copy of the wrapper with the provider binary substituted
        source = (WRAPPER_DIR / self.provider).read_text()
        self.wrapper = self.tmp / self.provider
        self.wrapper.write_text(
            source.replace(self.real_binary, str(self.cli_stub)))
        self._make_executable(self.wrapper)

        self.workspace_dir = self.home / '.config' / 'nubifer' / 'workspaces'
        self.workspace_dir.mkdir(parents=True)
        self.workspace_file = self.workspace_dir / f'{WORKSPACE_ID}.json'

        # Session Broker scoped AWS config (as exported by shell integration)
        providers = self.workspace_dir / WORKSPACE_ID / 'providers' / 'aws'
        providers.mkdir(parents=True)
        self.scoped_config = providers / 'config'
        self.scoped_config.write_text(
            "# Generated by NubiferOS workspace manager (Session Broker)\n"
            "[default]\nsso_session = nubifer\n")

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    # -- helpers ---------------------------------------------------------

    @staticmethod
    def _make_executable(path):
        path.chmod(path.stat().st_mode | stat.S_IXUSR)

    def write_workspace(self, sso=None, role_arn=None, session=None,
                        region='us-east-1'):
        data = {
            'id': WORKSPACE_ID,
            'name': WORKSPACE_NAME,
            'provider': 'aws',
            'region': region,
            'read_only': True,
        }
        if sso:
            data['sso'] = {'aws': sso}
        if role_arn:
            data['aws_role_arn'] = role_arn
        if session:
            data.setdefault('sessions', {})[self.provider_session_key()] = session
        self.workspace_file.write_text(json.dumps(data))

    def provider_session_key(self):
        return {'aws': 'aws', 'az': 'azure', 'gcloud': 'gcp'}[self.provider]

    def add_static_key(self, cred_name=WORKSPACE_NAME):
        """Simulate a static vault key (wrapper only checks file existence)"""
        key = (self.home / '.password-store' / 'nubifer' / WORKSPACE_ID /
               'cloud' / 'aws' / cred_name / 'access-key-id.gpg')
        key.parent.mkdir(parents=True)
        key.touch()

    def run_wrapper(self, args, read_only=False, broker_config=True):
        env = {
            'PATH': f"{self.stub_bin}:{os.environ.get('PATH', '')}",
            'HOME': str(self.home),
            'NUBIFER_WORKSPACE_ID': WORKSPACE_ID,
            'NUBIFER_WORKSPACE_NAME': WORKSPACE_NAME,
            'NUBIFER_TEST_RECORD': str(self.record),
        }
        if read_only:
            env['NUBIFER_WORKSPACE_READ_ONLY'] = 'true'
        if broker_config:
            # Shell integration exports the broker's scoped config path
            env['AWS_CONFIG_FILE'] = str(self.scoped_config)
        return subprocess.run(
            ['/bin/bash', str(self.wrapper)] + args,
            env=env, capture_output=True, text=True, timeout=60)

    def recorded(self):
        self.assertTrue(self.record.is_file(),
                        'provider CLI stub was never invoked')
        return self.record.read_text()

    def assert_not_invoked(self):
        self.assertFalse(self.record.is_file(),
                         'provider CLI stub must not run')


SSO_CONFIG = {
    'sso_start_url': 'https://example.awsapps.com/start',
    'sso_region': 'us-east-1',
    'sso_account_id': '123456789012',
    'sso_role_name': 'ReadOnly',
}

ACTIVE_SESSION = {
    'mode': 'sso',
    'identity': 'arn:aws:sts::123456789012:assumed-role/ReadOnly/alpha',
    'expires_at': _iso(+8),
    'logged_in_at': _iso(-1),
}

EXPIRED_SESSION = dict(ACTIVE_SESSION, expires_at=_iso(-2))

HINT_AWS = "session expired — run: nubifer-creds login -t aws"


class TestAwsSsoPassthrough(WrapperTestBase):
    """2.4a: SSO/role workspaces must keep the broker's scoped config."""

    def test_sso_workspace_does_not_override_broker_config(self):
        # Static vault key ALSO present: SSO config must still win (Req 4.1)
        self.write_workspace(sso=SSO_CONFIG, session=ACTIVE_SESSION)
        self.add_static_key()
        result = self.run_wrapper(['s3', 'ls'])
        self.assertEqual(result.returncode, 0, result.stderr)
        record = self.recorded()
        self.assertIn(f'AWS_CONFIG_FILE: {self.scoped_config}', record)
        # The broker config was passed through untouched, not a temp rewrite
        self.assertIn('sso_session = nubifer', record)
        self.assertNotIn('credential_process', record)

    def test_sso_config_without_session_still_passes_through(self):
        # SSO configured but not yet logged in: broker config still owns
        # resolution (aws will prompt for sso login itself)
        self.write_workspace(sso=SSO_CONFIG)
        self.add_static_key()
        result = self.run_wrapper(['sts', 'get-caller-identity'])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(f'AWS_CONFIG_FILE: {self.scoped_config}',
                      self.recorded())

    def test_role_binding_passes_through(self):
        # Role-profile path: broker config renders the role profile
        self.write_workspace(role_arn='arn:aws:iam::123456789012:role/Dev')
        self.add_static_key()
        result = self.run_wrapper(['s3', 'ls'])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(f'AWS_CONFIG_FILE: {self.scoped_config}',
                      self.recorded())

    def test_passthrough_exports_workspace_for_static_fallback(self):
        # 'nubifer-static' profile in the broker config still resolves via
        # credential_process, which needs NUBIFER_WORKSPACE
        self.write_workspace(sso=SSO_CONFIG, session=ACTIVE_SESSION)
        self.run_wrapper(['s3', 'ls'])
        self.assertIn(f'NUBIFER_WORKSPACE: {WORKSPACE_ID}', self.recorded())


class TestAwsStaticPathUnchanged(WrapperTestBase):
    """2.4a: static-only workspaces keep the legacy temp-config behavior."""

    def test_static_only_workspace_gets_wrapper_temp_config(self):
        self.write_workspace()  # no sso, no role, no session
        self.add_static_key()
        result = self.run_wrapper(['s3', 'ls'])
        self.assertEqual(result.returncode, 0, result.stderr)
        record = self.recorded()
        # Wrapper wrote its own temp config (NOT the broker path)
        self.assertNotIn(f'AWS_CONFIG_FILE: {self.scoped_config}', record)
        self.assertIn('credential_process = '
                      '/usr/local/bin/nubifer-aws-credential-helper '
                      f'{WORKSPACE_NAME}', record)
        self.assertIn('region = us-east-1', record)
        self.assertIn(f'NUBIFER_WORKSPACE: {WORKSPACE_ID}', record)

    def test_static_only_no_expired_hint(self):
        self.write_workspace()
        self.add_static_key()
        result = self.run_wrapper(['s3', 'ls'])
        self.assertNotIn('session expired', result.stderr)

    def test_no_credentials_at_all_runs_without_injection(self):
        self.write_workspace()
        result = self.run_wrapper(['s3', 'ls'])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('No AWS credentials found', result.stderr)
        self.recorded()


class TestAwsExpiredSessionHint(WrapperTestBase):
    """2.4b: one-line stderr hint on expired session; never blocks."""

    def test_expired_session_prints_hint_and_runs_command(self):
        self.write_workspace(sso=SSO_CONFIG, session=EXPIRED_SESSION)
        result = self.run_wrapper(['s3', 'ls'])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn(HINT_AWS, result.stderr)
        self.assertIn(WORKSPACE_NAME, result.stderr)
        # One line only
        hint_lines = [l for l in result.stderr.splitlines()
                      if 'session expired' in l]
        self.assertEqual(len(hint_lines), 1)
        # Command still ran (never block)
        self.assertIn('ARGS: s3 ls', self.recorded())

    def test_active_session_prints_no_hint(self):
        self.write_workspace(sso=SSO_CONFIG, session=ACTIVE_SESSION)
        result = self.run_wrapper(['s3', 'ls'])
        self.assertNotIn('session expired', result.stderr)

    def test_hint_never_prints_secrets(self):
        self.write_workspace(sso=SSO_CONFIG, session=EXPIRED_SESSION)
        result = self.run_wrapper(['s3', 'ls'])
        # Only non-secret metadata may surface: no start URL, no identity
        self.assertNotIn(SSO_CONFIG['sso_start_url'], result.stderr)
        self.assertNotIn(EXPIRED_SESSION['identity'], result.stderr)


class TestAwsReadOnlyAllPaths(WrapperTestBase):
    """3.4: read-only blocking is identical in all three credential paths
    and runs BEFORE any credential resolution or session logic."""

    def _assert_blocked(self, result):
        self.assertEqual(result.returncode, 1)
        self.assertIn('WRITE BLOCKED', result.stderr)
        self.assert_not_invoked()

    def test_blocked_static_temp_config_path(self):
        self.write_workspace()
        self.add_static_key()
        self._assert_blocked(
            self.run_wrapper(['s3', 'rm', 's3://bucket/key'], read_only=True))

    def test_blocked_sso_passthrough_path(self):
        self.write_workspace(sso=SSO_CONFIG, session=ACTIVE_SESSION)
        self._assert_blocked(
            self.run_wrapper(['ec2', 'terminate-instances',
                              '--instance-ids', 'i-123'], read_only=True))

    def test_blocked_role_profile_path(self):
        self.write_workspace(role_arn='arn:aws:iam::123456789012:role/Dev')
        self.add_static_key()
        self._assert_blocked(
            self.run_wrapper(['iam', 'create-user',
                              '--user-name', 'x'], read_only=True))

    def test_block_message_identical_across_paths(self):
        outputs = []
        for setup in (
                lambda: (self.write_workspace(), self.add_static_key()),
                lambda: self.write_workspace(sso=SSO_CONFIG,
                                             session=ACTIVE_SESSION),
                lambda: self.write_workspace(
                    role_arn='arn:aws:iam::123456789012:role/Dev')):
            setup()
            result = self.run_wrapper(['s3', 'rm', 's3://b/k'],
                                      read_only=True)
            self._assert_blocked(result)
            outputs.append(result.stderr)
        self.assertEqual(outputs[0], outputs[1])
        self.assertEqual(outputs[1], outputs[2])

    def test_enforcement_runs_before_session_expiry_logic(self):
        # Expired session + read-only write: the block must fire first, so
        # no re-login hint is printed (proves enforcement precedes all
        # credential/session resolution in the SSO passthrough path)
        self.write_workspace(sso=SSO_CONFIG, session=EXPIRED_SESSION)
        result = self.run_wrapper(['s3', 'rm', 's3://bucket/key'],
                                  read_only=True)
        self._assert_blocked(result)
        self.assertNotIn('session expired', result.stderr)

    def test_reads_still_allowed_in_read_only(self):
        self.write_workspace(sso=SSO_CONFIG, session=ACTIVE_SESSION)
        result = self.run_wrapper(['s3', 'ls'], read_only=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        self.recorded()


class TestAzExpiredSessionHint(WrapperTestBase):
    """2.4b applied to the az wrapper."""

    provider = 'az'
    real_binary = '/usr/bin/az'

    def test_expired_azure_session_prints_hint(self):
        self.write_workspace(
            session=dict(EXPIRED_SESSION, identity='user@example.com'))
        result = self.run_wrapper(['account', 'show'])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('session expired — run: nubifer-creds login -t azure',
                      result.stderr)
        self.assertIn(WORKSPACE_NAME, result.stderr)
        self.recorded()

    def test_active_azure_session_no_hint(self):
        self.write_workspace(session=dict(ACTIVE_SESSION))
        result = self.run_wrapper(['account', 'show'])
        self.assertNotIn('session expired', result.stderr)

    def test_read_only_block_precedes_hint(self):
        self.write_workspace(session=dict(EXPIRED_SESSION))
        result = self.run_wrapper(['vm', 'create', '-n', 'x'],
                                  read_only=True)
        self.assertEqual(result.returncode, 1)
        self.assertIn('WRITE BLOCKED', result.stderr)
        self.assertNotIn('session expired', result.stderr)
        self.assert_not_invoked()


class TestGcloudExpiredSessionHint(WrapperTestBase):
    """2.4b applied to the gcloud wrapper."""

    provider = 'gcloud'
    real_binary = '/usr/bin/gcloud'

    def test_expired_gcp_session_prints_hint(self):
        self.write_workspace(
            session=dict(EXPIRED_SESSION, identity='user@example.com'))
        result = self.run_wrapper(['projects', 'list'])
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn('session expired — run: nubifer-creds login -t gcp',
                      result.stderr)
        self.assertIn(WORKSPACE_NAME, result.stderr)
        self.recorded()

    def test_active_gcp_session_no_hint(self):
        self.write_workspace(session=dict(ACTIVE_SESSION))
        result = self.run_wrapper(['projects', 'list'])
        self.assertNotIn('session expired', result.stderr)

    def test_read_only_block_precedes_hint(self):
        self.write_workspace(session=dict(EXPIRED_SESSION))
        result = self.run_wrapper(['compute', 'instances', 'create', 'x'],
                                  read_only=True)
        self.assertEqual(result.returncode, 1)
        self.assertIn('WRITE BLOCKED', result.stderr)
        self.assertNotIn('session expired', result.stderr)
        self.assert_not_invoked()


if __name__ == '__main__':
    unittest.main()
