#!/usr/bin/env python3
"""
Offline unit tests for scoped provider config generation with modern auth
(SSO sessions and role/impersonation bindings) in nubifer-workspace.

Covers modern-cloud-auth Requirements 3.1-3.2 and 4.1:
- static-only workspaces keep the original byte-identical generated config
- SSO configuration renders an sso-session + default profile with the
  static credential_process profile as documented fallback (SSO > static)
- aws_role_arn produces a role-assumption default profile with the right
  source profile
- gcp_impersonate_service_account provisions the scoped gcloud config
- refresh_provider_configs regenerates marker-carrying files only

Same isolation as test_session_broker: temp HOME, mocked subprocess.run,
no network, no gpg/pass.
"""

import contextlib
import io
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import importlib.util
from importlib.machinery import SourceFileLoader

# nubifer-workspace has no .py extension - load it explicitly
_WS_PATH = str(Path(__file__).resolve().parent.parent / 'nubifer-workspace')
_loader = SourceFileLoader('nubifer_workspace_cfg', _WS_PATH)
_spec = importlib.util.spec_from_loader('nubifer_workspace_cfg', _loader)
nw = importlib.util.module_from_spec(_spec)
_loader.exec_module(nw)


class ProviderConfigTestCase(unittest.TestCase):
    """Base: isolated HOME, no subprocesses, no stdin."""

    def setUp(self):
        self.tmp_home = tempfile.mkdtemp(prefix='nubifer-test-home-')
        self._old_home = os.environ.get('HOME')
        os.environ['HOME'] = self.tmp_home

        self._subprocess_patch = mock.patch.object(
            nw.subprocess, 'run',
            return_value=mock.Mock(returncode=0, stdout='', stderr=''))
        self._subprocess_patch.start()

        self.manager = nw.WorkspaceManager()

    def tearDown(self):
        self._subprocess_patch.stop()
        if self._old_home is not None:
            os.environ['HOME'] = self._old_home
        else:
            os.environ.pop('HOME', None)
        shutil.rmtree(self.tmp_home, ignore_errors=True)

    # -- helpers ---------------------------------------------------------

    def _create_workspace(self, name='test-ws', provider='aws',
                          account_id='123456789012', region='us-east-1',
                          credential_id=None):
        with contextlib.redirect_stdout(io.StringIO()):
            workspace_id = self.manager.create_workspace(
                name=name,
                provider=provider,
                account_id=account_id,
                region=region,
                credential_id=credential_id,
                skip_confirm=True,
            )
        self.assertIsNotNone(workspace_id)
        return workspace_id

    def _update_workspace_json(self, workspace_id, **keys):
        """Simulate 'nubifer-creds login setup' writing workspace keys."""
        ws_file = self.manager.workspace_dir / f"{workspace_id}.json"
        with open(ws_file) as f:
            workspace = json.load(f)
        workspace.update(keys)
        with open(ws_file, 'w') as f:
            json.dump(workspace, f)
        return workspace

    def _aws_config(self, workspace_id):
        return (self.manager.workspace_dir / workspace_id / 'providers'
                / 'aws' / 'config')


class TestStaticConfigUnchanged(ProviderConfigTestCase):

    def test_static_only_config_is_byte_identical_to_original(self):
        """Static flow regression: no SSO/role keys -> original output."""
        workspace_id = self._create_workspace(region='us-west-2',
                                              credential_id='prod-cred')
        expected = (
            "# Generated by NubiferOS workspace manager (Session Broker)\n"
            f"# Workspace: {workspace_id}\n"
            "# Static credentials are resolved via credential_process from the\n"
            "# GPG/pass vault - no secrets are stored in this file.\n"
            "[default]\n"
            "credential_process = "
            "/usr/local/bin/nubifer-aws-credential-helper prod-cred\n"
            "region = us-west-2\n"
        )
        self.assertEqual(self._aws_config(workspace_id).read_text(), expected)


class TestSsoConfigGeneration(ProviderConfigTestCase):

    SSO = {'aws': {'sso_start_url': 'https://acme.awsapps.com/start',
                   'sso_region': 'us-east-1',
                   'sso_account_id': '123456789012',
                   'sso_role_name': 'DevAccess'}}

    def test_refresh_renders_sso_session_and_static_fallback(self):
        workspace_id = self._create_workspace()
        workspace = self._update_workspace_json(workspace_id, sso=self.SSO)

        self.assertTrue(
            self.manager.refresh_provider_configs(workspace_id, workspace))
        config = self._aws_config(workspace_id).read_text()

        self.assertIn('[sso-session nubifer]', config)
        self.assertIn('sso_start_url = https://acme.awsapps.com/start', config)
        self.assertIn('sso_region = us-east-1', config)
        self.assertIn('[default]', config)
        self.assertIn('sso_account_id = 123456789012', config)
        self.assertIn('sso_role_name = DevAccess', config)
        self.assertIn('[profile nubifer-static]', config)
        self.assertIn('credential_process = '
                      '/usr/local/bin/nubifer-aws-credential-helper default',
                      config)

    def test_precedence_default_is_sso_static_is_fallback_profile(self):
        """Req 4.1: [default] resolves via SSO; static only via profile."""
        workspace_id = self._create_workspace()
        workspace = self._update_workspace_json(workspace_id, sso=self.SSO)
        self.manager.refresh_provider_configs(workspace_id, workspace)
        config = self._aws_config(workspace_id).read_text()

        default_section = config.split('\n[default]\n')[1].split('[profile')[0]
        self.assertIn('sso_session = nubifer', default_section)
        self.assertNotIn('credential_process', default_section)
        # SSO default must come before the static fallback profile
        self.assertLess(config.index('\n[default]\n'),
                        config.index('[profile nubifer-static]'))

    def test_refresh_never_overwrites_user_edited_config(self):
        workspace_id = self._create_workspace()
        config_path = self._aws_config(workspace_id)
        config_path.write_text('# user-managed\n[default]\nregion = eu-central-1\n')

        workspace = self._update_workspace_json(workspace_id, sso=self.SSO)
        refreshed = self.manager.refresh_provider_configs(workspace_id, workspace)

        self.assertFalse(refreshed)
        self.assertIn('user-managed', config_path.read_text())

    def test_refresh_logs_provider_scope_audit_entry(self):
        workspace_id = self._create_workspace()
        workspace = self._update_workspace_json(workspace_id, sso=self.SSO)
        self.manager.refresh_provider_configs(workspace_id, workspace)

        log = self.manager.audit_log.read_text()
        self.assertIn('PROVIDER_SCOPE', log)
        self.assertIn('refreshed generated provider configs', log)


class TestRoleBindings(ProviderConfigTestCase):

    def test_role_arn_with_sso_uses_sso_source_profile(self):
        workspace_id = self._create_workspace()
        workspace = self._update_workspace_json(
            workspace_id,
            sso=TestSsoConfigGeneration.SSO,
            aws_role_arn='arn:aws:iam::123456789012:role/Deployer')
        self.manager.refresh_provider_configs(workspace_id, workspace)
        config = self._aws_config(workspace_id).read_text()

        default_section = config.split('\n[default]\n')[1].split('[profile')[0]
        self.assertIn('role_arn = arn:aws:iam::123456789012:role/Deployer',
                      default_section)
        self.assertIn('source_profile = nubifer-sso', default_section)
        self.assertIn('[profile nubifer-sso]', config)
        self.assertIn('[profile nubifer-static]', config)

    def test_role_arn_without_sso_uses_static_source_profile(self):
        workspace_id = self._create_workspace()
        workspace = self._update_workspace_json(
            workspace_id,
            aws_role_arn='arn:aws:iam::123456789012:role/ReadOnly')
        self.manager.refresh_provider_configs(workspace_id, workspace)
        config = self._aws_config(workspace_id).read_text()

        self.assertIn('source_profile = nubifer-static', config)
        self.assertNotIn('[sso-session', config)
        self.assertIn('[profile nubifer-static]', config)

    def test_gcp_impersonation_provisions_scoped_gcloud_config(self):
        workspace_id = self._create_workspace(
            name='gcp-ws', provider='gcp', account_id='my-project',
            region='us-central1')
        workspace = self._update_workspace_json(
            workspace_id,
            gcp_impersonate_service_account='deploy@my-project.iam.gserviceaccount.com')
        self.manager.refresh_provider_configs(workspace_id, workspace)

        gcloud_config = (self.manager.workspace_dir / workspace_id / 'providers'
                         / 'gcloud' / 'configurations' / 'config_default')
        self.assertTrue(gcloud_config.is_file())
        content = gcloud_config.read_text()
        self.assertIn('impersonate_service_account = '
                      'deploy@my-project.iam.gserviceaccount.com', content)
        self.assertIn('project = my-project', content)
        self.assertEqual(os.stat(gcloud_config).st_mode & 0o777, 0o600)

    def test_gcloud_config_untouched_without_impersonation_binding(self):
        workspace_id = self._create_workspace()
        gcloud_config = (self.manager.workspace_dir / workspace_id / 'providers'
                         / 'gcloud' / 'configurations' / 'config_default')
        self.assertFalse(gcloud_config.exists(),
                         "gcloud config must not be written without a binding")

    def test_gcloud_managed_config_not_overwritten(self):
        """Once gcloud rewrites the file (marker gone), leave it alone."""
        workspace_id = self._create_workspace(
            name='gcp-ws2', provider='gcp', account_id='other-project',
            region='us-central1')
        workspace = self._update_workspace_json(
            workspace_id,
            gcp_impersonate_service_account='sa@other-project.iam.gserviceaccount.com')
        gcloud_config = (self.manager.workspace_dir / workspace_id / 'providers'
                         / 'gcloud' / 'configurations' / 'config_default')
        gcloud_config.parent.mkdir(parents=True, exist_ok=True)
        gcloud_config.write_text('[core]\nproject = gcloud-managed\n')

        self.manager.refresh_provider_configs(workspace_id, workspace)
        self.assertEqual(gcloud_config.read_text(),
                         '[core]\nproject = gcloud-managed\n')


if __name__ == '__main__':
    unittest.main()
