#!/bin/bash
# NubiferOS Firejail Wrapper
# Generates workspace-specific Firejail profiles and wraps cloud CLI commands

set -e

NUBIFER_CONFIG_DIR="${HOME}/.config/nubifer"
FIREJAIL_PROFILE_DIR="${HOME}/.config/firejail"
SYSTEM_PROFILE_DIR="/etc/firejail/nubifer"

# Ensure directories exist
mkdir -p "${FIREJAIL_PROFILE_DIR}"
mkdir -p "${NUBIFER_CONFIG_DIR}/firejail-profiles"

# Function to generate workspace-specific Firejail profile
generate_workspace_profile() {
    local workspace_id="$1"
    local provider="$2"
    local workspace_file="${NUBIFER_CONFIG_DIR}/workspaces/${workspace_id}.json"
    
    if [ ! -f "$workspace_file" ]; then
        echo "✗ Workspace not found: $workspace_id" >&2
        return 1
    fi
    
    # Output profile path
    local profile_path="${FIREJAIL_PROFILE_DIR}/nubifer-${provider}-${workspace_id}.profile"
    
    # Start with base provider profile
    cat > "$profile_path" << EOF
# Auto-generated Firejail profile for workspace: ${workspace_id}
# Provider: ${provider}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT EDIT - This file is auto-generated by nubifer-workspace

# Include base provider profile
include ${SYSTEM_PROFILE_DIR}/nubifer-${provider}.profile

# Workspace-specific configuration
# Workspace ID: ${workspace_id}

# Whitelist this workspace's configuration
whitelist \${HOME}/.config/nubifer/workspaces/${workspace_id}.json
read-only \${HOME}/.config/nubifer/workspaces/${workspace_id}.json

# Whitelist this workspace's credentials directory
EOF

    # Add provider-specific credential paths
    case "$provider" in
        aws)
            cat >> "$profile_path" << EOF
whitelist \${HOME}/.aws/workspace-${workspace_id}
mkdir \${HOME}/.aws/workspace-${workspace_id}
whitelist \${HOME}/.aws/config
whitelist \${HOME}/.aws/credentials

# Blacklist other workspace AWS directories
EOF
            # Blacklist other workspaces
            for other_ws in "${NUBIFER_CONFIG_DIR}/workspaces"/*.json; do
                if [ -f "$other_ws" ]; then
                    other_id=$(basename "$other_ws" .json)
                    if [ "$other_id" != "$workspace_id" ]; then
                        echo "blacklist \${HOME}/.aws/workspace-${other_id}" >> "$profile_path"
                    fi
                fi
            done
            ;;
        
        azure)
            cat >> "$profile_path" << EOF
whitelist \${HOME}/.azure/workspace-${workspace_id}
mkdir \${HOME}/.azure/workspace-${workspace_id}

# Blacklist other workspace Azure directories
EOF
            for other_ws in "${NUBIFER_CONFIG_DIR}/workspaces"/*.json; do
                if [ -f "$other_ws" ]; then
                    other_id=$(basename "$other_ws" .json)
                    if [ "$other_id" != "$workspace_id" ]; then
                        echo "blacklist \${HOME}/.azure/workspace-${other_id}" >> "$profile_path"
                    fi
                fi
            done
            ;;
        
        gcp)
            cat >> "$profile_path" << EOF
whitelist \${HOME}/.config/gcloud/workspace-${workspace_id}
mkdir \${HOME}/.config/gcloud/workspace-${workspace_id}

# Blacklist other workspace GCP directories
EOF
            for other_ws in "${NUBIFER_CONFIG_DIR}/workspaces"/*.json; do
                if [ -f "$other_ws" ]; then
                    other_id=$(basename "$other_ws" .json)
                    if [ "$other_id" != "$workspace_id" ]; then
                        echo "blacklist \${HOME}/.config/gcloud/workspace-${other_id}" >> "$profile_path"
                    fi
                fi
            done
            ;;
        
        oracle)
            cat >> "$profile_path" << EOF
whitelist \${HOME}/.oci/workspace-${workspace_id}
mkdir \${HOME}/.oci/workspace-${workspace_id}

# Blacklist other workspace OCI directories
EOF
            for other_ws in "${NUBIFER_CONFIG_DIR}/workspaces"/*.json; do
                if [ -f "$other_ws" ]; then
                    other_id=$(basename "$other_ws" .json)
                    if [ "$other_id" != "$workspace_id" ]; then
                        echo "blacklist \${HOME}/.oci/workspace-${other_id}" >> "$profile_path"
                    fi
                fi
            done
            ;;
    esac
    
    # Add read-only restrictions if workspace is read-only
    local read_only=$(python3 -c "import json; ws=json.load(open('$workspace_file')); print('true' if ws.get('read_only', False) else 'false')")
    
    if [ "$read_only" = "true" ]; then
        cat >> "$profile_path" << EOF

# Read-only mode restrictions
# Make credential directories read-only
EOF
        case "$provider" in
            aws)
                echo "read-only \${HOME}/.aws/workspace-${workspace_id}" >> "$profile_path"
                ;;
            azure)
                echo "read-only \${HOME}/.azure/workspace-${workspace_id}" >> "$profile_path"
                ;;
            gcp)
                echo "read-only \${HOME}/.config/gcloud/workspace-${workspace_id}" >> "$profile_path"
                ;;
            oracle)
                echo "read-only \${HOME}/.oci/workspace-${workspace_id}" >> "$profile_path"
                ;;
        esac
    fi
    
    # Set secure permissions
    chmod 600 "$profile_path"
    
    echo "$profile_path"
}

# Function to wrap cloud CLI command with Firejail
wrap_command() {
    local provider="$1"
    shift
    local command="$@"
    
    # Check if workspace is active
    if [ -z "$NUBIFER_WORKSPACE_ID" ]; then
        echo "✗ No active workspace. Activate a workspace first:" >&2
        echo "  nubifer-workspace switch <workspace-id>" >&2
        echo "  eval \$(nubifer-workspace env <workspace-id>)" >&2
        return 1
    fi
    
    # Generate or update workspace profile
    local profile_path=$(generate_workspace_profile "$NUBIFER_WORKSPACE_ID" "$provider")
    
    if [ $? -ne 0 ]; then
        echo "✗ Failed to generate Firejail profile" >&2
        return 1
    fi
    
    # Check if Firejail is installed
    if ! command -v firejail &> /dev/null; then
        echo "⚠️  Firejail not installed. Running without isolation." >&2
        echo "   Install with: sudo apt-get install firejail" >&2
        # Fall back to running command directly
        exec "$@"
        return $?
    fi
    
    # Run command with Firejail isolation
    exec firejail --profile="$profile_path" "$@"
}

# Main execution
if [ $# -lt 2 ]; then
    echo "Usage: $0 <provider> <command> [args...]"
    echo "Providers: aws, azure, gcp, oracle"
    exit 1
fi

wrap_command "$@"
