---
efiBootLoader: "grub"
efiBootloaderId: "nubiferos"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true

# Timeout for bootloader installation
timeout: 120

# Don't fail installation if bootloader fails (can be fixed post-install)
# This is useful for testing in VMs
# Set to false for production
dontChroot: false
