---
# Fstab module configuration
# Generates /etc/fstab for the installed system

mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime,compress=zstd
    ext4: defaults,noatime,errors=remount-ro

ssdExtraMountOptions:
    ext4: discard
    btrfs: discard=async
    f2fs: discard

crypttabOptions: luks,discard
