---
efiSystemPartition:     "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
allowManualPartitioning:   true

initialPartitioningChoice: erase
initialSwapChoice: small

defaultFileSystemType:  "ext4"
defaultPartitionTableType: "gpt"

availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"

# Enable encryption by default
enableLuksAutomatedPartitioning: true
luksGeneration: luks2

# Require encryption (user cannot disable)
requiredStorageEncryption: true
