---
# Services configuration for systemd

# Services to enable
services:
  - name: "NetworkManager"
    mandatory: true
  - name: "gdm3"
    mandatory: true
  - name: "systemd-timesyncd"
    mandatory: false

# Services to disable
disable:
  - name: "calamares-autostart"
    mandatory: false

# Targets
targets:
  - name: "graphical"
    mandatory: true

# Disable services from live environment
disableTargetServices:
  - name: "live-config"
    mandatory: false
