---
# Setup encryption nag notifications if user bypassed encryption
# Runs at the end of installation, in chroot

dontChroot: false
timeout: 30

script:
    - command: "/usr/local/bin/calamares-setup-encryption-nag.sh"
      timeout: 30
