---
defaultGroups:
    - name: users
      must: false
    - name: lp
      must: false
    - name: video
      must: false
    - name: network
      must: false
    - name: storage
      must: false
    - name: wheel
      must: false
    - name: audio
      must: false
    - name: sudo
      must: true
    - name: docker
      must: false

autologinGroup:  autologin

doAutologin:     false

sudoersGroup:    sudo

setRootPassword: true

doReusePassword: true

passwordRequirements:
    minLength: 12
    maxLength: -1

allowWeakPasswords: false

userShell: /bin/bash

hostname:
    location: EtcFile
    writeHostsFile: true
    template: "nubiferos-${cpu}"

presets:
    fullName:
        value: ""
        editable: true
    loginName:
        value: ""
        editable: true
