# Calamares settings for NubiferOS

---
modules-search: [ local ]

instances:
- id:       nubiferos
  module:   packages
  config:   packages.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - packagechooser
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages@nubiferos
  - bootloader
  - umount
- show:
  - finished

branding: nubiferos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: true

hide-back-and-next-during-exec: true

quit-at-end: false
