# Calamares settings for NubiferOS

---
modules-search: [ local ]

instances:
- id:       nubiferos
  module:   packages
  config:   packages.conf
- id:       prepare-bootloader
  module:   shellprocess
  config:   prepare-bootloader.conf
- id:       prepare-devices
  module:   shellprocess
  config:   prepare-devices.conf
- id:       debug-devices
  module:   shellprocess
  config:   debug-devices.conf
- id:       fix-dev-mounts
  module:   shellprocess
  config:   fix-dev-mounts.conf
- id:       setup-encryption-nag
  module:   shellprocess
  config:   setup-encryption-nag.conf
- id:       post-install-cleanup
  module:   shellprocess
  config:   post-install-cleanup.conf
- id:       setup-recovery-key
  module:   shellprocess
  config:   setup-recovery-key.conf
- id:       copy-recovery-key
  module:   shellprocess
  config:   copy-recovery-key.conf
- id:       show-recovery-key
  module:   shellprocess
  config:   show-recovery-key.conf
- id:       check-encryption
  module:   shellprocess
  config:   check-encryption.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - netinstall
  - summary
- exec:
  - shellprocess@prepare-devices
  - partition
  - shellprocess@check-encryption
  - shellprocess@setup-recovery-key
  - mount
  - unpackfs
  - shellprocess@fix-dev-mounts
  - shellprocess@debug-devices
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - shellprocess@copy-recovery-key
  - shellprocess@show-recovery-key
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages@nubiferos
  - shellprocess@post-install-cleanup
  - shellprocess@setup-encryption-nag
  - initramfscfg
  - shellprocess@prepare-bootloader
  - shellprocess@log-bootloader-config
  - bootloader
  - umount
- show:
  - finished

# Testing minimal nubiferos branding
branding: nubiferos

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: true

hide-back-and-next-during-exec: true

quit-at-end: false
